Process Management - Configuration Files

{
 "autoplug/updater-config.yml": {
  "parser": "yaml",
   "find": {
    "updater-config.java-updater.enabled": "false",
    "updater-config.java-updater.profile": "AUTOMATIC",
    "updater-config.java-updater.version": "17",
    "updater-config.server-updater.enabled": "{{server.build.env.SERVER_UPDATE_ENABLE}}",
    "updater-config.server-updater.profile": "{{server.build.env.SERVER_UPDATE_PROFILE}}",
     "updater-config.server-updater.software": "{{server.build.env.SERVER_TYPE}}",
    "updater-config.plugins-updater.enable": "{{server.build.env.PLUGIN_UPDATE_ENABLE}}
    "updater-config.plugins-updater.profile": "{{server.build.env.PLUGIN_UPDATE_PROFILE}}